# 使用Euerka作为注册中心
server:
  port: 8001 # 指定运行端口
spring:
  application:
    name: eureka-registry # 指定服务名称
  security: # 配置SpringSecurity登录用户名和密码
    user:
      name: temp
      password: 123456
eureka:
  instance:
    hostname: localhost # 指定主机地址
  client:
    fetch-registry: false # 指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false # 指定是否要注册到注册中心（注册中心不需要开启）
