server:
  port: 8801
spring:
  application:
    name: temp-gateway
# 使用SpringCloud GateWay作为API网关
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true # 用小写服务名，默认是大写

# 使用Euerka作为注册中心(客户端)
# 默认注册中心地址格式：http://${hostname}:${port}/eureka/
# 注册到需要登录认证的Euerka注册中心时的地址格式：http://${username}:${password}@${hostname}:${port}/eureka/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://temp:123456@localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
# 使用zuul作为API网关
#zuul:
#  routes: # 给服务配置路由
#    temp-admin:
#      path: /tempAdmin/**
#    temp-xx-service:
#      path: /tempXxService/**
#  ignored-services: temp-admin,temp-xx-service # 关闭默认路由配置
#  prefix: /proxy # 给网关路由添加前缀
#  sensitive-headers: Cookie,Set-Cookie,Authorization # 配置过滤敏感的请求头信息，设置为空就不会过滤
#  add-host-header: true # 设置为true重定向是会添加host请求头
# 禁用的过滤器配置格式:zuul.filterClassName.filterType.disable.true
#  PreLogFilter:
#    pre:
#      disable: true # 禁用PreLogFilter过滤器
# 查看Zuul中的路由信息
# 通过访问http://localhost:8801/actuator/routes查看简单路由信息
# 通过访问http://localhost:8801/actuator/routes/details查看详细路由信息：
#management:
#  endpoints:
#    web:
#      exposure:
#        include: 'routes'
